RFoundation.PL.WEB/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using RFoundation.BLL.Interfaces.Entities;
using RFoundation.BLL.Interfaces.Services;

namespace RFoundation.PL.WEB.Controllers
{
    public class FriendController : Controller
    {
        public IFileService FileService => (IFileService) DependencyResolver.Current.GetService(typeof(IFileService));
        public IUserService UserService => (IUserService) DependencyResolver.Current.GetService(typeof(IUserService));
        string Name = Membership.GetUser()?.UserName ?? "Anon";
        private int Id => UserService.GetAll().FirstOrDefault(u => u.Login == Name).Id;
        private BllUser User => UserService.GetAll().FirstOrDefault(u => u.Login == Name);

        public IFriendService FriendService
            => (IFriendService) DependencyResolver.Current.GetService(typeof(IFriendService));

        public ActionResult FriendList()
        {
            var u = Membership.GetUser();

            return View(User.Friends);
        }

        public ActionResult FriendOfferList()
        {
            var u = Membership.GetUser();

            return PartialView(User.FriendRequests);
        }
        //TODO:POST
        public void AddToFriend(int friendId)
        {
            var friend = UserService.Get(friendId);
            if (friend.Friends == null)
                friend.Friends = new List<BllFriend>();
            if (User.Friends == null)
                User.Friends = new List<BllFriend>();
            if (User.Friends != null && friend.Friends != null)
            {
                FriendService.Create(new BllFriend() {FriendId = friendId, UserId = User.Id});
                FriendService.Create(new BllFriend() {FriendId = User.Id, UserId = friend.Id});
            }
        }

        [HttpPost]
        public void OfferFriendship(int id)
        {
//TODO:
            //var u = Membership.GetUser();
            //var user = UserService.GetEntity(u.UserName);
            //FriendService.OfferFriendship(user.Id, id);
        }

        [HttpPost]
        public ActionResult FriendSearch(string name)
        {
            //TODO: I Enumerable -> bad
            var users =
                    UserService.GetAll()
                        .Where(u => u.Email.Contains(name) || u.Login.Contains(name) || u.LastName.Contains(name))
                ;
            if (!users.Any())
                return HttpNotFound();

            return PartialView(users);
        }

        public void ShareFile(int friendId, int fileId)
        {
            //var u = Membership.GetUser();
            //var user = UserService.GetEntity(u.UserName);
            //FileService.(user.Id, friendId, fileId);
        }

        public ActionResult Search()
        {
            return View();
        }
    }
}

RFoundation.PL.WEB/Views/Friend/FriendList.cshtml
@model System.Collections.Generic.IEnumerable<RFoundation.BLL.Interfaces.Entities.BllFriend>

<h1>Friends</h1>


<ul>
    @if (Model != null)
    {
        foreach (var friend in Model)
        {
            <li>
                UserID:
                <li>@friend.UserId</li>
                <li>@friend.Id</li>
            </li>
        }
    }

</ul>

<div>
    @using (Ajax.BeginForm("FriendOfferList", new AjaxOptions { UpdateTargetId = "results" }))
    {
        <input type="submit" value="ShowOffers" />
    }
    <div id="results"></div>
</div>

@section scripts{
    @*Scripts.Render("~/Scripts/jquery-1.10.2.min.js");*@
    @*@Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js");*@
}

RFoundation.PL.WEB/Views/Friend/FriendOfferList.cshtml
@model System.Collections.Generic.IEnumerable<RFoundation.BLL.Interfaces.Entities.BllUser>

<div id="offerers">
    <ul>
        @if (Model != null)
        {

            foreach (var item in Model)
            {
                <li>
                    @item.Email
                    <p>ID</p>
                    @item.Id
                    @Ajax.ActionLink("Add", "AddToFriend", new { friendId = item.Id }, new AjaxOptions { HttpMethod = "POST" })
                </li>
            }
        }
    </ul>
</div>

RFoundation.PL.WEB/Views/Friend/FriendSearch.cshtml
@model IEnumerable<RFoundation.BLL.Interfaces.Entities.BllUser>
<div>
    @using (Ajax.BeginForm("FriendSearch", new AjaxOptions { UpdateTargetId = "results" }))
    {
        <input type="text" name="name" />
        <input type="submit" value="Search" />
    }
    <div id="results"></div>
</div>

    <ul>
        @if (Model != null)
        {
            <table id="myTable" class="col-md-8 table table-striped tablesorter table-hover">
                <thead class="thead-default">
                <tr>
                    <th class="header text-center">Login</th>
                    <th class="header text-center">First Name</th>
                    <th class="header text-center">Last Name</th>
                </tr>
                </thead>
                <tbody>
                    
                    @foreach (var friend in Model)
                    {

                    <tr>
                        <td class="container text-center col-sm-6">
                            @friend.Login
                            <div class="menu ">
                                @*@Ajax.ActionLink("", "AddToFriend", "Friend", new { friendId = friend.Id }, new AjaxOptions { HttpMethod = "POST" })*@


                                @Html.ActionLink(" ", "Index", "Home", new { id = friend.Id }, new { @class = "glyphicon glyphicon-plus", style = "color: green;" })

                            </div>
                        </td>
                        <td class="text-center">@friend.FirstName</td>
                        <td class="text-center">@friend.FirstName</td>

                    </tr>
                    
                    @*@using (Ajax.BeginForm("Upload","Home",FormMethod.Post, new AjaxOptions() { UpdateTargetId = "results" }, new {enctype = "multipart/form-data" }))
        {
            <label class="btn btn-default btn-file upload">
                Browse <input type="file" name="upload" style="display: none;">
            </label>

            <label class="btn btn-default btn-file">
                Download<input id="upload" type="submit" value="Загрузить" style="display: none;" />
            </label>
        }*@
                    }

                </tbody>
            </table>
        }
    </ul>

RFoundation.PL.WEB/Views/Friend/Search.cshtml
<div>
    @using (Ajax.BeginForm("FriendSearch", new AjaxOptions { UpdateTargetId = "results" }))
    {
        <input type="text" name="name" />
        <input type="submit" value="Search" />
    }
    <div id="results"></div>
</div>

@section scripts{
    @*Scripts.Render("~/Scripts/jquery-1.10.2.min.js");*@
    @*@Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js");*@
}